import type { TripJournal, TripSettings } from '../types';
import { showToast } from './toast';
import { escapeHtml } from './utils';
import { getExportBudgetBreakdown, getTripDisplayEndpoints } from './trip-summary-view';
import { resolveJournalEntryLocation } from './journal-trip-view';
import type { JournalExportSummary, SegmentLookupSummary } from './trip-summary-slices';

/**
 * Export the trip journal as a downloadable HTML file.
 */
export function exportJournalAsHTML(journal: TripJournal, summary: SegmentLookupSummary): void {
  const journalHTML = `
<!DOCTYPE html>
<html>
<head>
  <title>${escapeHtml(journal.metadata.title)}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #2563eb; }
    .stop { border-left: 3px solid #10b981; padding-left: 15px; margin: 20px 0; }
    .highlight { background: #fef3c7; padding: 10px; border-radius: 8px; }
    .rating { color: #f59e0b; }
  </style>
</head>
<body>
  <h1>🚗 ${escapeHtml(journal.metadata.title)}</h1>
  <p><strong>Distance:</strong> ${journal.tripSummary.totalDistanceKm.toFixed(1)} km |
     <strong>Duration:</strong> ${(journal.tripSummary.totalDurationMinutes / 60).toFixed(1)} hours</p>
  <p><strong>Travelers:</strong> ${escapeHtml(journal.metadata.travelers?.join(', ') || 'Unknown')}</p>

  <h2>Journey Highlights</h2>
  ${journal.entries.map(e => {
    const stop = resolveJournalEntryLocation(summary, e);
    const photosHTML = e.photos.length > 0
      ? `<div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 10px; margin: 15px 0;">
          ${e.photos.map(p => `
            <div>
              <img src="${p.dataUrl}" alt="${escapeHtml(p.caption || 'Photo')}" style="width: 100%; height: 150px; object-fit: cover; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);" />
              ${p.caption ? `<p style="font-size: 12px; color: #6b7280; margin-top: 4px; text-align: center;">${escapeHtml(p.caption)}</p>` : ''}
            </div>
          `).join('')}
         </div>`
      : '';

    return `
    <div class="stop ${e.isHighlight ? 'highlight' : ''}">
      <h3>${escapeHtml(stop?.name || 'Unknown')}</h3>
      ${e.rating ? `<div class="rating">${'⭐'.repeat(e.rating)}</div>` : ''}
      ${photosHTML}
      ${e.notes ? `<p>${escapeHtml(e.notes)}</p>` : ''}
      ${e.isHighlight ? `<p><strong>✨ ${escapeHtml(e.highlightReason || '')}</strong></p>` : ''}
      <p><em>Status: ${e.status}</em></p>
    </div>`;
  }).join('')}

  ${journal.quickCaptures.length > 0 ? `
  <h2>📍 Memories Along the Way</h2>
  ${journal.quickCaptures.map(qc => {
    const mapsLink = qc.gpsCoords
      ? `https://www.google.com/maps?q=${qc.gpsCoords.lat},${qc.gpsCoords.lng}`
      : qc.photo?.location && (qc.photo.location.lat !== 0 || qc.photo.location.lng !== 0)
        ? `https://www.google.com/maps?q=${qc.photo.location.lat},${qc.photo.location.lng}`
        : null;
    return `
    <div style="border-left: 3px solid #a855f7; padding-left: 15px; margin: 15px 0;">
      <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 6px;">
        <strong>${escapeHtml(qc.autoTaggedLocation || 'Quick Memory')}</strong>
        ${qc.category ? `<span style="font-size: 11px; background: #f3e8ff; color: #7c3aed; padding: 2px 6px; border-radius: 9999px;">${escapeHtml(qc.category)}</span>` : ''}
        ${mapsLink ? `<a href="${mapsLink}" style="font-size: 11px; color: #2563eb;">📍 View on Maps</a>` : ''}
      </div>
      ${qc.photo ? `<img src="${qc.photo.dataUrl}" alt="${escapeHtml(qc.photo.caption || 'Memory')}" style="width: 100%; max-width: 400px; height: 200px; object-fit: cover; border-radius: 8px; margin-bottom: 6px;" />` : ''}
      ${qc.photo?.caption ? `<p style="margin: 4px 0; color: #374151;">${escapeHtml(qc.photo.caption)}</p>` : ''}
      ${qc.gpsCoords ? `<p style="font-size: 11px; color: #9ca3af;">GPS: ${qc.gpsCoords.lat.toFixed(5)}, ${qc.gpsCoords.lng.toFixed(5)}</p>` : ''}
    </div>`;
  }).join('')}
  ` : ''}

  <h2>Trip Statistics</h2>
  <ul>
    <li>Total Stops: ${journal.stats.stopsVisited + journal.stats.stopsSkipped}</li>
    <li>Stops Visited: ${journal.stats.stopsVisited}</li>
    <li>Photos Captured: ${journal.stats.photosCount}</li>
    <li>Highlights: ${journal.stats.highlightsCount}</li>
  </ul>

  <p style="text-align: center; color: #6b7280; margin-top: 40px;">
    Generated by My Experience Engine on ${new Date().toLocaleDateString()}
  </p>
</body>
</html>`;

  const blob = new Blob([journalHTML], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const safeTitle = journal.metadata.title
    // eslint-disable-next-line no-control-regex
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 100) || 'untitled';
  link.download = `roadtrip-journal-${safeTitle}.html`;
  link.click();
  URL.revokeObjectURL(url);

  showToast({
    message: 'Journal exported! Open the HTML file and print to PDF (Ctrl+P)',
    type: 'success',
    duration: 4000,
  });
}

/**
 * Export the trip as a loadable JSON template that others can import.
 */
export function exportJournalAsTemplate(journal: TripJournal, summary: JournalExportSummary, settings: TripSettings): void {
  const endpoints = getTripDisplayEndpoints(summary);
  const exportBudget = getExportBudgetBreakdown(summary);

  const template = {
    type: 'roadtrip-template',
    version: '1.0',
    createdAt: new Date().toISOString(),
    author: journal.metadata.travelers?.[0] || 'Anonymous',

    trip: {
      title: journal.metadata.title,
      description: journal.metadata.description || 'Follow this roadtrip route!',
      tags: journal.metadata.tags,
      durationDays: journal.tripSummary.days?.length || 1,
      totalDistanceKm: journal.tripSummary.totalDistanceKm,
      totalDurationHours: (journal.tripSummary.totalDurationMinutes / 60).toFixed(1),
    },

    budget: {
      profile: settings.budget.profile,
      totalSpent: journal.stats.totalActualSpent,
      perPerson: journal.stats.totalActualSpent / settings.numTravelers,
      breakdown: exportBudget,
    },

    route: {
      origin: endpoints.origin,
      destination: endpoints.destination,
      waypoints: summary.segments
        .map(s => s.to)
        .filter((loc, idx, arr) => arr.findIndex(l => l.name === loc.name) === idx),
    },

    recommendations: journal.entries.map(e => {
      const stop = resolveJournalEntryLocation(summary, e);
      return {
        location: stop?.name,
        lat: stop?.lat,
        lng: stop?.lng,
        rating: e.rating,
        notes: e.notes,
        isHighlight: e.isHighlight,
        highlightReason: e.highlightReason,
        wouldStayAgain: e.rating && e.rating >= 4,
        tips: e.notes,
      };
    }).filter(r => r.rating || r.isHighlight),

    // Include settings & vehicle so the plan can be fully loaded
    settings: {
      units: settings.units,
      currency: settings.currency,
      maxDriveHours: settings.maxDriveHours,
      numTravelers: settings.numTravelers,
      numDrivers: settings.numDrivers,
      isRoundTrip: settings.isRoundTrip,
      avoidTolls: settings.avoidTolls,
      avoidBorders: settings.avoidBorders,
      scenicMode: settings.scenicMode,
      routePreference: settings.routePreference,
      stopFrequency: settings.stopFrequency,
      gasPrice: settings.gasPrice,
      hotelPricePerNight: settings.hotelPricePerNight,
      mealPricePerDay: settings.mealPricePerDay,
    },

    vehicle: journal.vehicle,

    importInstructions: 'Load this template in My Experience Engine to follow the same route!',
  };

  const dataBlob = new Blob([JSON.stringify(template, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement('a');
  link.href = url;
  const safeName = journal.metadata.title
    // eslint-disable-next-line no-control-regex
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 100) || 'untitled';
  link.download = `trip-template-${safeName}.json`;
  link.click();
  URL.revokeObjectURL(url);

  showToast({
    message: 'Trip template downloaded! Share it so others can follow your route.',
    type: 'success',
    duration: 4000,
  });
}
