/**
 * trip-print-builders.ts — HTML generation helpers for the print view.
 *
 * These functions produce the raw HTML string injected into the print popup.
 * No React, no DOM — pure string templates.
 */

import type { TripSummary, TripSettings, TripDay } from '../types';
import type { DriverRotationResult } from './driver-rotation';
import type { TimedEvent } from './trip-timeline';
import { formatDriveTime } from './driver-rotation';
import { buildDayHTML } from './trip-print-day';
import { formatCurrency, formatDistance } from './trip-print-formatters';
import { PRINT_STYLES } from './trip-print-styles';

// ── Top-level HTML envelope ───────────────────────────────────────────────────

function buildTripBudgetStatus(summary: TripSummary, settings: TripSettings): string {
  if (settings.budgetMode !== 'plan-to-budget' || settings.budget.total <= 0) return '';
  if (summary.budgetRemaining === undefined || !summary.costBreakdown) return '';

  const statusLabel = summary.budgetRemaining < 0
    ? `Over total budget by ${formatCurrency(Math.abs(summary.budgetRemaining))}`
    : `Total budget remaining: ${formatCurrency(summary.budgetRemaining)}`;

  return `
    <div class="budget-overview">
      <strong>Budget target: ${formatCurrency(settings.budget.total)}</strong>
      &nbsp;|&nbsp;
      ${statusLabel}
    </div>
  `;
}

export function buildPrintHTML(
  tripTitle: string,
  summary: TripSummary,
  settings: TripSettings,
  days: TripDay[],
  driverRotation: DriverRotationResult | null,
  timedEvents: TimedEvent[],
): string {
  const units = settings.units;
  let runningTripSpend = 0;

  const overviewHTML = `
    <div class="overview">
      <h1>🗺️ ${tripTitle}</h1>
      <div class="stats-row">
        <span>📏 ${formatDistance(summary.totalDistanceKm, units)}</span>
        <span>⏱️ ${formatDriveTime(summary.totalDurationMinutes)} driving</span>
        <span>⛽ ${formatCurrency(summary.totalFuelCost)} fuel</span>
        <span>👥 ${settings.numTravelers} traveler${settings.numTravelers > 1 ? 's' : ''}</span>
        ${settings.numDrivers > 1 ? `<span>🔁 ${settings.numDrivers} drivers</span>` : ''}
        <span>📅 ${days.length} day${days.length !== 1 ? 's' : ''}</span>
      </div>
      ${summary.costBreakdown ? `
        <div class="budget-overview">
          <strong>Trip Total: ${formatCurrency(summary.costBreakdown.total)}</strong>
          (${formatCurrency(summary.costBreakdown.total / settings.numTravelers)}/person)
          &nbsp;|&nbsp;
          ⛽ ${formatCurrency(summary.costBreakdown.fuel)} fuel &nbsp;
          🏨 ${formatCurrency(summary.costBreakdown.accommodation)} hotel &nbsp;
          🍽️ ${formatCurrency(summary.costBreakdown.meals)} food &nbsp;
          📦 ${formatCurrency(summary.costBreakdown.misc)} misc
        </div>
      ` : ''}
      ${buildTripBudgetStatus(summary, settings)}
    </div>
  `;

  const daysHTML = days.map(day => {
    runningTripSpend += day.budget.dayTotal;
    const tripBudgetRemaining = settings.budgetMode === 'plan-to-budget' && settings.budget.total > 0
      ? settings.budget.total - runningTripSpend
      : undefined;
    return buildDayHTML(day, settings, driverRotation, units, timedEvents, tripBudgetRemaining);
  }).join('\n');

  let driverHTML = '';
  if (driverRotation && driverRotation.stats.length > 1) {
    driverHTML = `
      <div class="section driver-stats">
        <h2>🔁 Driver Rotation Summary</h2>
        <table>
          <thead>
            <tr><th>Driver</th><th>Drive Time</th><th>Distance</th><th>Segments</th></tr>
          </thead>
          <tbody>
            ${driverRotation.stats.map(s => `
              <tr>
                <td>Driver ${s.driver}</td>
                <td>${formatDriveTime(s.totalMinutes)}</td>
                <td>${formatDistance(s.totalKm, units)}</td>
                <td>${s.segmentCount}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
    `;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${tripTitle} — Trip Itinerary</title>
  <style>${PRINT_STYLES}</style>
</head>
<body>
  ${overviewHTML}
  ${daysHTML}
  ${driverHTML}
  <footer>
    <p>Generated by My Experience Engine • ${new Date().toLocaleDateString()}</p>
  </footer>
</body>
</html>`;
}
