/**
 * trip-print-builders.ts — HTML generation helpers for the print view.
 *
 * These functions produce the raw HTML string injected into the print popup.
 * No React, no DOM — pure string templates.
 *
 * Structure:
 *   Page 1 — cover page (buildCoverPageHTML): route, budget health, warnings, pacing, roster
 *   Page 2+ — day-by-day itinerary (buildDayHTML × N)
 */

import type { TripSummary, TripSettings, TripDay, Vehicle } from '../types';
import type { DriverRotationResult } from './driver-rotation';
import type { TimedEvent } from './trip-timeline';
import { buildDayHTML } from './trip-print-day';
import { PRINT_STYLES } from './trip-print-styles';
import { buildCoverPageHTML } from './trip-print-cover';
import { analyzeFeasibility } from './feasibility';

export function buildPrintHTML(
  tripTitle: string,
  summary: TripSummary,
  settings: TripSettings,
  days: TripDay[],
  driverRotation: DriverRotationResult | null,
  timedEvents: TimedEvent[],
  vehicle?: Vehicle,
): string {
  const units = settings.units;
  let runningTripSpend = 0;

  const feasibility = analyzeFeasibility(summary, settings);
  const coverHTML = buildCoverPageHTML(tripTitle, summary, settings, feasibility, driverRotation, vehicle);

  const daysHTML = days.map(day => {
    runningTripSpend += day.budget.dayTotal;
    const tripBudgetRemaining = settings.budgetMode === 'plan-to-budget' && settings.budget.total > 0
      ? settings.budget.total - runningTripSpend
      : undefined;
    return buildDayHTML(day, settings, driverRotation, units, timedEvents, tripBudgetRemaining);
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${tripTitle} — Trip Itinerary</title>
  <style>${PRINT_STYLES}</style>
</head>
<body>
  ${coverHTML}
  <h2 class="itinerary-header">📋 Day-by-Day Itinerary</h2>
  ${daysHTML}
  <footer>
    <p>Generated by My Experience Engine • ${new Date().toLocaleDateString()}</p>
  </footer>
</body>
</html>`;
}
