/**
 * trip-print-builders.ts — HTML generation helpers for the print view.
 *
 * These functions produce the raw HTML string injected into the print popup.
 * No React, no DOM — pure string templates.
 *
 * Structure:
 *   Page 1 — cover page (buildCoverPageHTML): route, budget health, warnings, pacing, roster
 *   Page 2+ — day-by-day itinerary (buildDayHTML × N)
 */

import type { DriverRotationResult } from './driver-rotation';
import { computeSwapAssignments } from './driver-rotation';
import type { PrintInput } from './canonical-trip';
import type { TimedEvent } from './trip-timeline';
import { buildDayHTML } from './trip-print-day';
import { PRINT_STYLES } from './trip-print-styles';
import { buildCoverPageHTML } from './trip-print-cover';
import { analyzeFeasibility } from './feasibility';

export function buildPrintHTML(
  tripTitle: string,
  printInput: PrintInput,
  driverRotation: DriverRotationResult | null,
  timedEvents: TimedEvent[],
): string {
  const {
    summary,
    days,
    inputs: { settings, vehicle },
  } = printInput;
  const itineraryDays = days.map(day => day.meta);
  const units = settings.units;
  let runningTripSpend = 0;

  // Compute driver swap suggestions for accepted fuel/combo events.
  // Collect accepted fuel stop references in time order, distribute unassigned
  // drivers round-robin — same logic as the itinerary view's swapSuggestions.
  const swapSuggestions: Record<string, number> =
    driverRotation && settings.numDrivers > 1
      ? computeSwapAssignments(
          timedEvents
            .filter(e => (e.type === 'fuel' || e.type === 'combo') && e.stops[0])
            .sort((a, b) => a.arrivalTime.getTime() - b.arrivalTime.getTime())
            .map(e => ({ id: e.stops[0].id })),
          driverRotation,
          settings.numDrivers,
        )
      : {};

  const feasibility = analyzeFeasibility(summary, settings);
  const coverHTML = buildCoverPageHTML(
    tripTitle, summary, settings, feasibility, driverRotation, vehicle,
    undefined,
    printInput.subtitle,
    printInput.tripRead,
  );

  const daysHTML = itineraryDays.map(day => {
    runningTripSpend += day.budget.dayTotal;
    const tripBudgetRemaining = settings.budgetMode === 'plan-to-budget' && settings.budget.total > 0
      ? settings.budget.total - runningTripSpend
      : undefined;
    return buildDayHTML(day, settings, driverRotation, units, timedEvents, tripBudgetRemaining, swapSuggestions, settings.driverNames);
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${tripTitle} — Trip Itinerary</title>
  <style>${PRINT_STYLES}</style>
</head>
<body>
  ${coverHTML}
  <h2 class="itinerary-header">📋 Day-by-Day Itinerary</h2>
  ${daysHTML}
  <footer>
    <p>Generated by My Experience Engine • ${new Date().toLocaleDateString()}</p>
  </footer>
</body>
</html>`;
}
